import numpy as np
import matplotlib.pyplot as plt
import r3f
from pathlib import Path

from src.ins.trajectories import figure_eight_curvilinear, figure_eight_attitude
from src.ins.mechanization import forward_mechanize
from src.ins.plotting import save_figure, configure_axes

"""
Forward Mechanization Demonstration

This example validates the strapdown inertial navigation mechanization
equations by reconstructing an aircraft trajectory from synthetic IMU
measurements generated by inverse mechanization.

Starting from:

- initial position,
- initial attitude,
- initial velocity,
- accelerometer measurements,
- and gyroscope measurements,

the navigation solution is propagated forward and compared against the
original truth trajectory.

This experiment demonstrates the complete INS simulation loop:

Truth Trajectory
    -> Inverse Mechanization
    -> Synthetic IMU Data
    -> Forward Mechanization
    -> Reconstructed Trajectory
"""

def plot_geodetic_trajectory(llh_est):
    fig, ax = plt.subplots()
    ax.plot(llh_est[:,1]*180/np.pi, llh_est[:,0]*180/np.pi)
    configure_axes(
        ax,
        xlabel="Longitude (deg)",
        ylabel="Latitude (deg)",
        title="Reconstructed Geodetic Trajectory"
    )
    ax = plt.gca()
    ax.get_yaxis().get_major_formatter().set_useOffset(False)   # disables scientific notation
    return fig


def plot_geodetic_error(t, llh_est, llh_truth):
    fig, ax = plt.subplots()
    ax.plot(t/60, llh_est[:,0]-llh_truth[:,0], label="Latitude Error (rad)")
    ax.plot(t/60, llh_est[:,1]-llh_truth[:,1], label="Longitude Error (rad)")
    ax.plot(t/60, llh_est[:,2]-llh_truth[:,2], label="Height Above Ellipsoid Error (m)")
    configure_axes(
        ax,
        xlabel="Time (min)",
        ylabel="Geodetic Errors",
        title="Geodetic Position Errors"
    )
    ax.legend()
    return fig


def plot_attitude_error(t, rpy_est, rpy_truth):
    fig, ax = plt.subplots()
    ax.plot(t/60, rpy_est[:,0]-rpy_truth[:,0], label="Roll Error (rad)")
    ax.plot(t/60, rpy_est[:,1]-rpy_truth[:,1], label="Pitch Error (rad)")
    ax.plot(t/60, rpy_est[:,2]-rpy_truth[:,2], label="Yaw Error (rad)")
    configure_axes(
        ax,
        xlabel="Time (min)",
        ylabel="Euler Errors",
        title="Attitude Errors"
    )
    ax.legend()
    return fig


def plot_velocity_error(t, vne_est, vne_truth):
    fig, ax = plt.subplots()
    ax.plot(t/60, vne_est[:,0]-vne_truth[:,0], label="x-velocity error (m/s)")
    ax.plot(t/60, vne_est[:,1]-vne_truth[:,1], label="y-velocity error (m/s)")
    ax.plot(t/60, vne_est[:,2]-vne_truth[:,2], label="z-velocity error (m/s)")
    configure_axes(
        ax,
        xlabel="Time (min)",
        ylabel="Velocity Errors (m/s)",
        title="Velocity Errors"
    )
    ax.legend()
    return fig


def run_demo():

    DATA_FILE = Path("data/data_fbbi_wbbi_vne.bin")

    # Simulation parameters
    T = 0.1                 # sampling period (s)
    t_dur = 360.0           # simulation duration (s)

    # Initial aircraft geodetic position
    lat0 = 39.535*np.pi/180
    lon0 = -76.348*np.pi/180
    hae0 = 212.0
    llh0 = np.array([lat0, lon0, hae0])

    # Load synthetic IMU measurements generated by the inverse
    # mechanization experiment.
    #
    # Each row contains:
    #
    # [f_bbi, w_bbi, v_ne]
    #
    # where:
    #   f_bbi = accelerometer measurements
    #   w_bbi = gyroscope measurements
    #   v_ne  = truth navigation velocity
    M = np.fromfile(DATA_FILE).reshape((-1, 9))
    K = M.shape[0]
    fbbi_t = M[:,:3]
    wbbi_t = M[:,3:6]
    vne_truth = M[:,6:]

    # Reconstruct the original truth trajectory used to generate
    # the synthetic IMU data.
    K = round(t_dur/T) + 1
    theta = np.linspace(0, 2*np.pi, K)
    xyz_truth = figure_eight_curvilinear(theta).T
    llh_truth = r3f.curvilinear_to_geodetic(xyz_truth, llh0)
    rpy_truth = figure_eight_attitude(theta)
    rpy0 = rpy_truth[0]


    # Perform forward mechanization.
    #
    # The mechanization is initialized using the truth initial state and
    # propagated using the synthetic IMU measurements.
    #
    # The truth altitude trajectory is also provided as ideal altitude aiding,
    # analogous to a perfect barometric altimeter measurement.
    #
    # This prevents vertical-channel drift from dominating the experiment and
    # allows validation of the core mechanization equations.
    llh_est, vne_est, rpy_est, Cnb_est = forward_mechanize(fbbi_t, wbbi_t, vne_truth, llh_truth, rpy0, T)

    # time array
    t = np.arange(K) * T

    # Compare the reconstructed navigation solution against the
    # original truth trajectory.
    fig = plot_geodetic_trajectory(llh_est)
    save_figure(fig, "results/figures/forward_mechanization_demo", "reconstructed_geodetic_trajectory")

    fig = plot_geodetic_error(t, llh_est, llh_truth)
    save_figure(fig, "results/figures/forward_mechanization_demo", "geodetic_error")

    fig = plot_attitude_error(t, rpy_est, rpy_truth)
    save_figure(fig, "results/figures/forward_mechanization_demo", "attitude_error")

    fig = plot_velocity_error(t, vne_est, vne_truth)
    save_figure(fig, "results/figures/forward_mechanization_demo", "velocity_error")


if __name__=="__main__":
    run_demo()
    # plt.show()