import numpy as np
import matplotlib.pyplot as plt
import r3f
from pathlib import Path
from tqdm import tqdm

from src.ins.noise import (
    allan_windows,
    allan_variance,
    generate_quantization_noise,
    generate_white_noise,
    generate_fogm_noise,
    generate_brownian_noise,
    generate_ramp_noise,
)
from src.ins.mechanization import forward_mechanize
from src.ins.trajectories import figure_eight_curvilinear, figure_eight_attitude
from src.ins.plotting import configure_axes, save_figure

"""
Noisy IMU Modeling and INS Error Propagation Demonstration

This example investigates the effects of stochastic IMU errors on
inertial navigation performance.

Part I focuses on sensor characterization by generating common inertial
sensor noise processes and validating their statistical properties using:

- Monte Carlo simulation,
- standard deviation analysis,
- and Allan variance analysis.

Part II injects these noise processes into synthetic IMU measurements
and studies how sensor errors propagate through a strapdown inertial
navigation system.

The overall objective is to bridge the gap between ideal inertial
navigation and realistic inertial navigation.
"""


def plot_noise(t, noise, ylabel, title):
    fig, ax = plt.subplots()
    ax.hexbin(t/60, noise*1e6, cmap=plt.cm.Blues, mincnt=1, linewidths=0)
    configure_axes(
        ax,
        xlabel="Time (min)",
        ylabel=ylabel,
        title=title
    )
    return fig


def plot_std(t, noise, ylabel, title):
    fig, ax = plt.subplots()
    ax.plot(t/60, noise*1e6)
    configure_axes(
        ax,
        xlabel="Time (min)",
        ylabel=ylabel,
        title=title
    )
    return fig

def plot_allan_variance(tau, va, vi, vm, vf):
    fig, ax = plt.subplots()
    for i in range(va.shape[0]):
        if i==0:
            ax.plot(tau, va[i], color='blue', label="Monte")
        else:
            ax.plot(tau, va[i], color='blue')
    ax.plot(tau, vi, label="ideal")
    ax.plot(tau, vm, label="mean")
    ax.plot(tau, vf, label="fit")
    configure_axes(
        ax,
        xlabel="Averaging time, $\\tau$ (s)",
        ylabel="Allan variance (rad$^2$/s$^2$)",
        title="Allan Variance Fit"
    )
    ax.legend()
    ax.set_xscale("log")
    ax.set_yscale("log")
    return fig


def run_sensor_demo(noise_dict, tau_f, dt, t_dur, mc_runs):
    """
    Generate and validate stochastic IMU noise processes.

    This experiment models several common inertial sensor error sources
    and evaluates their statistical properties using Monte Carlo
    simulation and Allan variance analysis.

    The following noise processes are considered:

    - Quantization noise
    - White noise
    - Bias instability (FOGM)
    - Brownian noise (rate random walk)
    - Ramp noise
    """

    # Simulation timeline.
    #
    # K is the number of discrete samples used for each Monte Carlo
    # realization.
    K = int(t_dur/dt)
    t = np.arange(0, t_dur, dt)

    # Quantization Noise
    #
    # Quantization noise arises from finite sensor resolution and
    # represents the smallest measurable change in sensor output.
    n_q = np.zeros((mc_runs, K))
    for i in range(mc_runs):
        n_q[i] = generate_quantization_noise(noise_dict['sigma_q'], K, dt)

    fig = plot_noise(t, n_q, ylabel="Quantization ($\\mu$rad/s)", title="Quantization Noise")
    save_figure(fig, "results/figures/noisy_imu_demo", "quantization_noise")

    # White Noise
    #
    # White noise models random sample-to-sample measurement uncertainty
    # and is typically the dominant short-term IMU error source.
    n_rw = np.zeros((mc_runs, K))
    for i in range(mc_runs):
        n_rw[i] = generate_white_noise(noise_dict['sigma_rw'], K, dt)

    fig = plot_noise(t, n_rw, ylabel="White ($\\mu$rad/s)", title="White Noise")
    save_figure(fig, "results/figures/noisy_imu_demo", "white_noise")

    # Bias Instability (First-Order Gauss-Markov)
    #
    # Bias instability is modeled as a correlated stochastic process
    # with finite memory. This captures slowly varying sensor bias.
    n_f = np.zeros((mc_runs, K))
    for i in range(mc_runs):
        n_f[i] = generate_fogm_noise(noise_dict['sigma_f'], K, dt, tau_f)

    fig = plot_noise(t, n_f, ylabel="FOGM ($\\mu$rad/s)", title="Bias Instability (FOGM) Noise")
    save_figure(fig, "results/figures/noisy_imu_demo", "fogm_noise")

    # Brownian Noise (Rate Random Walk)
    #
    # Brownian noise is generated by integrating white noise and
    # produces long-term random drift.
    n_b = np.zeros((mc_runs, K))
    for i in range(mc_runs):
        n_b[i] = generate_brownian_noise(noise_dict['sigma_b'], K, dt)

    fig = plot_noise(t, n_b, ylabel="Brownian ($\\mu$rad/s)", title="Brownian Noise")
    save_figure(fig, "results/figures/noisy_imu_demo", "brownian_noise")

    # Ramp Noise
    #
    # Ramp noise models a continuously drifting sensor bias and
    # dominates sensor behavior at very long averaging times.
    n_r = np.zeros((mc_runs, K))
    for i in range(mc_runs):
        n_r[i] = generate_ramp_noise(noise_dict['sigma_r'], K, dt)

    fig = plot_noise(t, n_r, ylabel="Ramp ($\\mu$rad/s)", title="Ramp Noise")
    save_figure(fig, "results/figures/noisy_imu_demo", "ramp_noise")

    # Bias Instability Validation
    #
    # Verify that the generated FOGM process converges to the expected
    # steady-state standard deviation.
    fig = plot_std(t, np.std(n_f, axis=0), ylabel="Bias instability $\\sigma$ ($\\mu$rad/s)", title="Bias Instability Validation")
    save_figure(fig, "results/figures/noisy_imu_demo", "fogm_std")

    # Brownian Noise Validation
    #
    # Verify the expected variance growth behavior associated with a
    # rate random walk process.
    y = np.sqrt(np.var(n_b, axis=0)/(t + 1e-9))
    y[0] = y[1]
    fig = plot_std(t, y, ylabel="Rate random walk $\\sigma$ ($\\mu$ rad/s)", title="Brownian Noise Validation")
    save_figure(fig, "results/figures/noisy_imu_demo", "brownian_validation")

    # Allan Variance Analysis
    #
    # Combine all stochastic error sources into a single sensor model
    # and estimate the underlying noise parameters using Allan variance.

    # Composite sensor error model.
    #
    # This signal contains all modeled noise processes and represents
    # the output of a realistic inertial sensor.
    n_t = n_q + n_rw + n_f + n_b + n_r
    M = allan_windows(K)
    va = np.zeros((mc_runs, len(M)))
    for j in range(mc_runs):
        va[j,:] = allan_variance(n_t[j,:], M)
    tau = M*dt
    vm = np.mean(va, axis=0)

    q = np.exp(-dt/tau_f)
    ff = (M*(1 - q)**2 + 2*q*M*(1 - q)- 2*q*(1 - q**M) - q*(1 - q**M)**2)/((M**2)*((1 - q)**2))
    # Allan variance basis functions corresponding to:
    #
    #   Quantization noise
    #   White noise
    #   Bias instability (FOGM)
    #   Brownian noise
    #   Ramp noise
    H = np.array([
        3/tau**2,
        1/tau,
        ff,
        tau/3,
        tau**2/2]).T
    
    vi = H @ np.array([noise_dict['sigma_q'], 
                       noise_dict['sigma_rw'], 
                       noise_dict['sigma_f'],
                       noise_dict['sigma_b'],
                       noise_dict['sigma_r']])**2
    # Estimate the stochastic noise parameters using a least-squares fit
    # to the mean Allan variance curve.
    kF = np.abs(np.linalg.inv(H.T @ H) @ H.T @ vm)
    vf = H @ kF

    # print fitted sigmas
    print(f"fitted sigma_q:  {np.sqrt(kF[0]):.4g} rad")
    print(f"fitted sigma_rw: {np.sqrt(kF[1]):.4g} rad/s^0.5")
    print(f"fitted sigma_f:  {np.sqrt(kF[2]):.4g} rad/s")
    print(f"fitted sigma_b:  {np.sqrt(kF[3]):.4g} rad/s^1.5")
    print(f"fitted sigma_r:  {np.sqrt(kF[4]):.4g} rad/s^2")

    fig = plot_allan_variance(tau, va, vi, vm, vf)
    save_figure(fig, "results/figures/noisy_imu_demo", "allan_variance_fit")


def apply_noise_case(fbbi_truth, wbbi_truth, noise, case, accel_scale=1000.0):
    """
    Add one composite noise realization to selected accelerometer/gyro axes.
    """
    fbbi_noisy = fbbi_truth.copy()
    wbbi_noisy = wbbi_truth.copy()

    for axis in case["gyro_axes"]:
        wbbi_noisy[:, axis] += noise[:, axis]

    for axis in case["accel_axes"]:
        fbbi_noisy[:, axis] += accel_scale * noise[:, axis]

    return fbbi_noisy, wbbi_noisy


def run_noisy_flight_case(case_config, noise_dict, truth_data, dt, tau_f, num_runs=10):
    """
    Run Monte Carlo noisy forward mechanization for one sensor-noise case.
    """
    K = truth_data["accel"].shape[0]

    curv_runs = np.zeros((num_runs, K, 3))
    vertical_error_runs = np.zeros((num_runs, K))

    for i in range(num_runs):
        noise = generate_noise(noise_dict, axes=3, K=K, dt=dt, tau_f=tau_f)

        fbbi_noisy, wbbi_noisy = apply_noise_case(
            truth_data["accel"],
            truth_data["gyro"],
            noise,
            case_config,
        )

        llh_est, vne_est, rpy_est, Cnb_est = forward_mechanize(
            fbbi_noisy,
            wbbi_noisy,
            truth_data["vel"],
            truth_data["llh"],
            truth_data["rpy0"],
            dt,
        )

        curv_est = r3f.geodetic_to_curvilinear(llh_est, truth_data["llh"][0])
        curv_runs[i] = curv_est

        vertical_error_runs[i] = curv_est[:, 2] - truth_data["curv_truth"][:, 2]

    return curv_runs, vertical_error_runs


def generate_noise(noise_dict, axes, K, dt=0.1, tau_f=5*(3/np.pi)):
    """
    Generate composite IMU noise for multiple sensor axes.

    Returns
    -------
    noise : ndarray, shape (K, axes)
        Composite noise time history for each requested axis.
    """
    noise = np.zeros((K, axes))

    for axis in range(axes):
        n_q = generate_quantization_noise(noise_dict["sigma_q"], K, dt)
        n_rw = generate_white_noise(noise_dict["sigma_rw"], K, dt)
        n_f = generate_fogm_noise(noise_dict["sigma_f"], K, dt, tau_f)
        n_b = generate_brownian_noise(noise_dict["sigma_b"], K, dt)
        n_r = generate_ramp_noise(noise_dict["sigma_r"], K, dt)

        noise[:, axis] = n_q + n_rw + n_f + n_b + n_r

    return noise


def plot_noisy_horizontal_trajectories(curv_runs, curv_truth, title):
    fig, ax = plt.subplots()

    for i in range(curv_runs.shape[0]):
        label = "Monte Carlo" if i == 0 else None
        ax.plot(
            curv_runs[i, :, 1] / 1000,
            curv_runs[i, :, 0] / 1000,
            color="blue",
            label=label,
        )

    ax.plot(
        curv_truth[:, 1] / 1000,
        curv_truth[:, 0] / 1000,
        color="red",
        label="Truth",
    )

    configure_axes(
        ax,
        xlabel="Curvilinear $y_c$ (km)",
        ylabel="Curvilinear $x_c$ (km)",
        title=title,
        equal=True,
    )
    ax.legend()
    return fig


def plot_noisy_vertical_errors(t, vertical_error_runs, title):
    fig, ax = plt.subplots()

    for i in range(vertical_error_runs.shape[0]):
        label = "Monte Carlo" if i == 0 else None
        ax.plot(t / 60, vertical_error_runs[i], color="blue", label=label)

    configure_axes(
        ax,
        xlabel="Time (min)",
        ylabel="Vertical Error, $\\Delta z_c$ (m)",
        title=title,
    )
    ax.legend()
    return fig


def run_flight_demo(noise_dict, tau_f, dt, t_dur):
    OUTPUT_DIR = Path("results/figures/noisy_imu_demo")

    lat0 = 39.535 * np.pi / 180
    lon0 = -76.348 * np.pi / 180
    hae0 = 212.0
    llh0 = np.array([lat0, lon0, hae0])

    DATA_FILE = Path("data/data_fbbi_wbbi_vne.bin")
    M = np.fromfile(DATA_FILE).reshape((-1, 9))

    fbbi_truth = M[:, :3]
    wbbi_truth = M[:, 3:6]
    vne_truth = M[:, 6:]

    K = fbbi_truth.shape[0]
    t = np.arange(K) * dt

    theta = np.linspace(0, 2 * np.pi, K)
    curv_truth = figure_eight_curvilinear(theta).T
    # llh_truth is passed to forward_mechanize only for initial position
    # and ideal altitude aiding. Latitude and longitude are not used as
    # correction measurements during propagation.
    llh_truth = r3f.curvilinear_to_geodetic(curv_truth, llh0)
    rpy_truth = figure_eight_attitude(theta)

    truth_data = {
        "accel": fbbi_truth,
        "gyro": wbbi_truth,
        "vel": vne_truth,
        "llh": llh_truth,
        "rpy0": rpy_truth[0],
        "curv_truth": curv_truth,
    }

    NOISE_CASES = {
        "gyro_all":  {"gyro_axes": [0, 1, 2], "accel_axes": []},
        "gyro_x":    {"gyro_axes": [0],       "accel_axes": []},
        "gyro_y":    {"gyro_axes": [1],       "accel_axes": []},
        "gyro_z":    {"gyro_axes": [2],       "accel_axes": []},
        "accel_all": {"gyro_axes": [],        "accel_axes": [0, 1, 2]},
        "accel_x":   {"gyro_axes": [],        "accel_axes": [0]},
        "accel_y":   {"gyro_axes": [],        "accel_axes": [1]},
        "accel_z":   {"gyro_axes": [],        "accel_axes": [2]},
        "all":       {"gyro_axes": [0, 1, 2], "accel_axes": [0, 1, 2]},
    }

    for case_name, case_config in tqdm(NOISE_CASES.items()):
        curv_runs, z_err_runs = run_noisy_flight_case(
            case_config,
            noise_dict,
            truth_data,
            dt=dt,
            tau_f=tau_f,
            num_runs=10,
        )

        fig = plot_noisy_horizontal_trajectories(
            curv_runs,
            curv_truth,
            title=f"{case_name}: Horizontal Trajectories",
        )
        save_figure(fig, OUTPUT_DIR, f"{case_name}_horizontal")
        plt.close(fig)

        fig = plot_noisy_vertical_errors(
            t,
            z_err_runs,
            title=f"{case_name}: Vertical Error",
        )
        save_figure(fig, OUTPUT_DIR, f"{case_name}_vertical")
        plt.close(fig)



def run_demo():
    np.random.seed(2)

    # Gyroscope noise parameters.
    sigma_q = 4.18e-7 * (np.pi/180)             # quantization noise (rad)
    sigma_rw = 4.47e-4 * (np.pi/180) / (60)     # white noise (rad/s^0.5)
    sigma_f = 7.22e-2 * (np.pi/180) / (3600)    # fogm noise (rad/s)
    sigma_b = 2.72 * (np.pi/180) / (60*3600)    # brownian noise (rad/s^1.5)
    sigma_r = 13.4 * (np.pi/180) / (3600**2)    # ramp noise (rad/s^2)
    noise_dict = {'sigma_q': sigma_q, 
                  'sigma_rw': sigma_rw,
                  'sigma_f': sigma_f,
                  'sigma_b': sigma_b,
                  'sigma_r': sigma_r}

    # Simulation parameters
    tau_f = 5*(3/np.pi)  # bias instability time constant (s)
    dt = 10e-3           # sampling period (s)
    t_dur = 200          # duration (s)
    mc_runs = 100        # number of monte carlo runs

    run_sensor_demo(noise_dict, tau_f, dt, t_dur, mc_runs)

    run_flight_demo(noise_dict, tau_f, dt=0.1, t_dur=360.0)



if __name__=="__main__":
    run_demo()