from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt
import r3f
from tqdm import tqdm

from src.ins.earth import somigliana
from src.ins.mechanization import forward_mechanize
from src.ins.plotting import configure_axes, save_figure

"""
Schuler Oscillation Demonstration

This example investigates how sensor biases and initialization errors
propagate through an Earth-referenced inertial navigation system.

A stationary aircraft is simulated for six hours while various
accelerometer biases, gyroscope biases, and navigation-state errors
are introduced individually. The resulting trajectories illustrate
the emergence of Schuler oscillation and provide intuition for the
coupling between attitude, velocity, and position errors.

Topics demonstrated:

- Schuler oscillation
- Accelerometer bias effects
- Gyroscope bias effects
- Navigation-state initialization errors
- Earth-curvature error dynamics
"""

OUTPUT_DIR = Path("results/figures/schuler_oscillation_demo")

SCHULER_CASES = {
    "accel_x_bias": {"type": "accel_bias", "axis": 0, "value": 1e-3, "title": "Accelerometer X-Axis Bias"},
    "accel_y_bias": {"type": "accel_bias", "axis": 1, "value": 1e-3, "title": "Accelerometer Y-Axis Bias"},
    "gyro_x_bias": {"type": "gyro_bias", "axis": 0, "value": 1e-6, "title": "Gyroscope X-Axis Bias"},
    "gyro_y_bias": {"type": "gyro_bias", "axis": 1, "value": 1e-6, "title": "Gyroscope Y-Axis Bias"},
    "gyro_z_bias": {"type": "gyro_bias", "axis": 2, "value": 1e-6, "title": "Gyroscope Z-Axis Bias"},
    "initial_latitude_error": {"type": "llh_error", "axis": 0, "value": 1e-3, "title": "Initial Latitude Error"},
    "initial_longitude_error": {"type": "llh_error", "axis": 1, "value": 1e-3, "title": "Initial Longitude Error"},
    "initial_vn_error": {"type": "velocity_error", "axis": 0, "value": 1e-3, "title": "Initial North Velocity Error"},
    "initial_ve_error": {"type": "velocity_error", "axis": 1, "value": 1e-3, "title": "Initial East Velocity Error"},
    "initial_roll_error": {"type": "attitude_error", "axis": 0, "value": 1e-3, "title": "Initial Roll Error"},
    "initial_pitch_error": {"type": "attitude_error", "axis": 1, "value": 1e-3, "title": "Initial Pitch Error"},
    "initial_yaw_error": {"type": "attitude_error", "axis": 2, "value": 1e-3, "title": "Initial Yaw Error"},
}

def generate_stationary_truth(llh0, dt, t_dur):
    """
    Generate truth IMU measurements for a stationary aircraft.

    The aircraft remains motionless on the Earth's surface for the
    duration of the simulation. The resulting accelerometer and
    gyroscope measurements contain only gravity and Earth rotation.

    Parameters
    ----------
    llh0 : ndarray, shape (3,)
        Initial geodetic position [latitude, longitude, height].

    dt : float
        Simulation sample period (s).

    t_dur : float
        Total simulation duration (s).

    Returns
    -------
    fbbi_truth : ndarray, shape (K, 3)
        Ideal body-frame specific force measurements (m/s²).

    wbbi_truth : ndarray, shape (K, 3)
        Ideal body-frame angular-rate measurements (rad/s).

    llh0 : ndarray, shape (3,)
        Initial geodetic position.

    vne0 : ndarray, shape (3,)
        Initial navigation-frame velocity (m/s).

    rpy0 : ndarray, shape (3,)
        Initial roll, pitch, and yaw angles (rad).

    t : ndarray, shape (K,)
        Simulation time vector (s).
    """
    vne0 = np.array([0.0, 0, 0])
    rpy0 = np.array([0.0, 0, 0])

    # time array
    K = round(t_dur/dt) + 1
    t = np.arange(K)*dt

    # sensor values
    gravz = -1*somigliana(llh0[0], llh0[2])
    fbbi = np.array([0.0, 0.0, gravz])
    wbbi = np.array([r3f.W_EI*np.cos(llh0[0]), 0, -1*r3f.W_EI*np.sin(llh0[0])])
    fbbi_truth = np.outer(fbbi, np.ones(K)).T
    wbbi_truth = np.outer(wbbi, np.ones(K)).T

    return (fbbi_truth, wbbi_truth, llh0, vne0, rpy0, t)


def apply_schuler_case(case, truth_data):
    """
    Apply a Schuler-oscillation test case to the truth data.

    Depending on the selected case, either a sensor bias or an
    initialization error is introduced into the navigation system.

    Parameters
    ----------
    case : dict
        Case definition from SCHULER_CASES.

    truth_data : tuple
        Nominal stationary-aircraft truth data generated by
        generate_stationary_truth().

    Returns
    -------
    fbbi_case : ndarray
        Accelerometer measurements with the specified perturbation.

    wbbi_case : ndarray
        Gyroscope measurements with the specified perturbation.

    llh0_case : ndarray
        Initial geodetic position after applying the perturbation.

    vne0_case : ndarray
        Initial velocity after applying the perturbation.

    rpy0_case : ndarray
        Initial attitude after applying the perturbation.
    """
    fbbi_case = truth_data[0].copy()
    wbbi_case = truth_data[1].copy()
    llh0_case = truth_data[2].copy()
    vne0_case = truth_data[3].copy()
    rpy0_case = truth_data[4].copy()

    if case["type"]=="accel_bias":
        axis = case["axis"]
        val = case["value"]
        fbbi_case[:,axis] += val
    elif case["type"]=="gyro_bias":
        axis = case["axis"]
        val = case["value"]
        wbbi_case[:,axis] += val
    elif case["type"]=="llh_error":
        axis = case["axis"]
        val = case["value"]
        llh0_case[axis] += val
    elif case["type"]=="velocity_error":
        axis = case["axis"]
        val = case["value"]
        vne0_case[axis] += val
    elif case["type"]=="attitude_error":
        axis = case["axis"]
        val = case["value"]
        rpy0_case[axis] += val

    return fbbi_case, wbbi_case, llh0_case, vne0_case, rpy0_case


def run_schuler_case(case_config, truth_data, dt):
    """
    Execute a single Schuler-oscillation experiment.

    The selected perturbation is applied to the nominal truth data,
    after which the forward mechanization algorithm propagates the
    navigation solution for the full simulation duration.

    Parameters
    ----------
    case_config : dict
        Configuration describing the perturbation to apply.

    truth_data : tuple
        Nominal stationary-aircraft truth data.

    dt : float
        Simulation sample period (s).

    Returns
    -------
    llh_est : ndarray
        Estimated geodetic trajectory.

    vne_est : ndarray
        Estimated navigation-frame velocity history.

    rpy_est : ndarray
        Estimated attitude history.

    curv_est : ndarray
        Estimated curvilinear trajectory relative to the true position.
    """
    fbbi_case, wbbi_case, llh0_case, vne0_case, rpy0_case = apply_schuler_case(case_config, truth_data)
    # Construct the inputs required by forward_mechanize().
    #
    # This experiment assumes a stationary aircraft, so the true geodetic
    # position does not change with time. However, forward_mechanize()
    # expects a full LLH time history because the same function is used
    # elsewhere for moving-aircraft simulations and altitude aiding.
    #
    # We therefore replicate the initial position across all timesteps to
    # create a constant reference trajectory.
    #
    # The initial velocity is also reshaped into a single-row array because
    # forward_mechanize() expects the initial navigation state in that form.
    llh_truth = truth_data[2].copy()
    llh_case = np.tile(llh0_case, (fbbi_case.shape[0], 1))
    vne0_case = vne0_case.reshape((1, -1))
    llh_est, vne_est, rpy_est, Cnb_est = forward_mechanize(fbbi_case, wbbi_case, vne0_case, llh_case, rpy0_case, dt)
    curv_est = r3f.geodetic_to_curvilinear(llh_est, llh_truth)

    return llh_est, vne_est, rpy_est, curv_est


def plot_schuler_trajectory(curv_est, title):
    fig, ax = plt.subplots()

    ax.scatter(
        curv_est[0,1]/1000,
        curv_est[0,0]/1000,
        color="red",
        s=20,
        zorder=2,
        label="Start"
    )

    ax.plot(
        curv_est[:, 1] / 1000,
        curv_est[:, 0] / 1000,
        zorder=1
    )

    configure_axes(
        ax,
        xlabel="Curvilinear $y_c$ (km)",
        ylabel="Curvilinear $x_c$ (km)",
        title=title,
        equal=True,
    )
    ax.legend(loc='best')
    return fig


def plot_schuler_case_summary(summary):

    summary = sorted(summary, key=lambda item: item["max_error_m"])

    case_labels = [item["case"] for item in summary]
    max_errors_km = [item["max_error_m"] / 1000 for item in summary]

    fig, ax = plt.subplots(figsize=(9, 6))
    ax.barh(case_labels, max_errors_km)

    configure_axes(
        ax,
        xlabel="Maximum Horizontal Error (km)",
        ylabel="Schuler Test Case",
        title="Maximum Horizontal Error by Case",
    )

    return fig


def run_demo():
    dt = 1.0
    t_dur = 6.0 * 60.0 * 60.0
    llh0 = np.array([39.535*(np.pi/180), -76.348*(np.pi/180), 212.0])

    truth_data = generate_stationary_truth(llh0, dt, t_dur)

    summary = []

    for case_name, case_config in tqdm(SCHULER_CASES.items()):
        llh_est, vne_est, rpy_est, curv_est = run_schuler_case(
            case_config,
            truth_data,
            dt,
        )

        horizontal_error = np.linalg.norm(curv_est[:, :2], axis=1)

        summary.append({
            "case": case_config["title"],
            "final_error_m": horizontal_error[-1],
            "max_error_m": np.max(horizontal_error),
            "mean_error_m": np.mean(horizontal_error),
        })

        fig = plot_schuler_case_summary(summary)
        save_figure(fig, OUTPUT_DIR, "schuler_case_summary")
        plt.close(fig)

        fig = plot_schuler_trajectory(curv_est, case_config["title"])
        save_figure(fig, OUTPUT_DIR, f"{case_name}_xy")
        plt.close(fig)

    for item in sorted(summary, key=lambda x: x["max_error_m"], reverse=True):
        print(
            f"{item['case']:<30} "
            f"final={item['final_error_m']/1000:8.3f} km  "
            f"max={item['max_error_m']/1000:8.3f} km  "
            f"mean={item['mean_error_m']/1000:8.3f} km"
        )


if __name__=="__main__":
    run_demo()